### ISSUE TITLE
No google play store in version 0.5.0

### ISSUE THREAD

**Issue by yurivict** [doozan/NookManager#4]
I installed 0.5.0 on Nook 1.2.1, it looks great.
However, without google play app installing apps becomes more difficult.

Care to publish HOWTO on how to install google play app? It is better if this is tested in centralized way, not by each user individually.

Or maybe just add it into the NookManager distro?

**Comment by doozan** [comment]
http://forum.xda-developers.com/showthread.php?t=2086582
