### ISSUE TITLE
Is there somewhere to download for windows?

### ISSUE THREAD

**Issue by KieranBrannigan** [doozan/NookManager#7]
I've came from the xda-developers forums where this application was posted: https://forum.xda-developers.com/t/root-nookmanager-graphical-rooter-for-1-2-x-and-beyond.2040351/

However the download link in that post seems to be dead.

I don't have a linux system at hand to build it myself so I was wondering if there is anywhere it can be downloaded for windows.

Kind regards,
Kieran

**Comment by JpTiger** [comment]
It's in the first post you linked to, but isn't totally obvious. Click the words "Nook Manager" in the first step.

**Comment by KieranBrannigan** [comment]
Ah yes, the link was working again a couple days later. I forgot to close this issue. But thanks hopefully this can help people find it in future.
